package com.sktech.wastetrack.ui.screens.compliance

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.sktech.wastetrack.data.local.db.dao.CertificateDao
import com.sktech.wastetrack.data.local.db.dao.TransferDao
import com.sktech.wastetrack.data.local.db.entity.CertificateEntity
import com.sktech.wastetrack.data.local.db.entity.TransferEntity
import com.sktech.wastetrack.util.Constants
import com.sktech.wastetrack.util.HashUtils
import com.google.gson.Gson
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.*
import kotlinx.coroutines.launch
import java.util.UUID
import javax.inject.Inject

data class ComplianceState(
    val certificates: List<CertificateEntity> = emptyList(),
    val completedTransfers: List<TransferEntity> = emptyList(),
    val isGenerating: Boolean = false,
    val selectedCertificate: CertificateEntity? = null,
    val error: String? = null,
    val successMessage: String? = null
)

@HiltViewModel
class ComplianceViewModel @Inject constructor(
    private val certificateDao: CertificateDao,
    private val transferDao: TransferDao,
    private val authRepository: com.sktech.wastetrack.domain.repository.IAuthRepository
) : ViewModel() {

    private var activeFactoryId = Constants.DEFAULT_FACTORY_ID

    private val _state = MutableStateFlow(ComplianceState())
    val state: StateFlow<ComplianceState> = _state.asStateFlow()

    init {
        viewModelScope.launch {
            val user = authRepository.getCurrentUser()
            val isRecycler = user?.role == com.sktech.wastetrack.domain.model.UserRole.RECYCLER
            activeFactoryId = user?.factoryId?.ifBlank { Constants.DEFAULT_FACTORY_ID } ?: Constants.DEFAULT_FACTORY_ID

            if (isRecycler && user != null) {
                // Recycler: show all certificates (generated via weight verification)
                launch {
                    certificateDao.getAllCertificates().collect { certs ->
                        _state.update { it.copy(certificates = certs) }
                    }
                }
                launch {
                    transferDao.getByRecycler(user.id).collect { transfers ->
                        _state.update { it.copy(completedTransfers = transfers.filter { t -> t.status == "VERIFIED" || t.status == "DELIVERED" }) }
                    }
                }
            } else {
                // Supervisor: show factory certificates
                launch {
                    certificateDao.getByFactory(activeFactoryId).collect { certs ->
                        _state.update { it.copy(certificates = certs) }
                    }
                }
                launch {
                    transferDao.getByFactory(activeFactoryId).collect { transfers ->
                        _state.update { it.copy(completedTransfers = transfers.filter { t -> t.status == "VERIFIED" || t.status == "DELIVERED" }) }
                    }
                }
            }
        }
    }

    fun generateCertificateForTransfer(transfer: TransferEntity) {
        viewModelScope.launch {
            _state.update { it.copy(isGenerating = true) }
            try {
                // Check if cert already exists
                val existing = certificateDao.getByTransferId(transfer.id)
                if (existing != null) {
                    _state.update { it.copy(isGenerating = false, error = "Certificate already exists for this transfer") }
                    return@launch
                }

                val certId = UUID.randomUUID().toString()
                val now = System.currentTimeMillis()
                val targetFactory = if (transfer.fromFactoryId.isNotBlank()) transfer.fromFactoryId else activeFactoryId

                // Build MPCB-format JSON payload
                val payload = mapOf(
                    "certificateId" to certId,
                    "type" to "MPCB_DISPOSAL",
                    "factoryId" to targetFactory,
                    "factoryName" to "Ambad MIDC Pilot Unit",
                    "mpcbRegNumber" to "MPCB/MH/NAS/2024/001234",
                    "transferId" to transfer.id,
                    "scrapEntryId" to transfer.scrapEntryId,
                    "weightDisposedKg" to transfer.weightAtSource,
                    "disposalMethod" to "Certified Recycler Transfer",
                    "vehicleNumber" to transfer.vehicleNumber,
                    "disposalDate" to now,
                    "complianceOfficer" to "Auto-Generated by WasteTrack",
                    "verificationHash" to transfer.contentHash
                )

                val jsonPayload = Gson().toJson(payload)
                val signature = HashUtils.sha256(jsonPayload)

                val certificate = CertificateEntity(
                    id = certId,
                    transferId = transfer.id,
                    factoryId = targetFactory,
                    type = "MPCB_DISPOSAL",
                    jsonPayload = jsonPayload,
                    digitalSignature = signature,
                    status = "GENERATED",
                    generatedAt = now
                )

                certificateDao.insert(certificate)

                _state.update {
                    it.copy(
                        isGenerating = false,
                        successMessage = "MPCB certificate generated successfully"
                    )
                }
            } catch (e: Exception) {
                _state.update { it.copy(isGenerating = false, error = e.message) }
            }
        }
    }

    fun generateBulkCertificates() {
        viewModelScope.launch {
            _state.update { it.copy(isGenerating = true) }
            var generated = 0
            for (transfer in _state.value.completedTransfers) {
                val existing = certificateDao.getByTransferId(transfer.id)
                if (existing == null) {
                    generateCertificateForTransfer(transfer)
                    generated++
                }
            }
            _state.update {
                it.copy(
                    isGenerating = false,
                    successMessage = if (generated > 0) "$generated certificates generated" else "All transfers already have certificates"
                )
            }
        }
    }

    fun selectCertificate(cert: CertificateEntity) {
        _state.update { it.copy(selectedCertificate = cert) }
    }

    fun clearSelection() {
        _state.update { it.copy(selectedCertificate = null) }
    }

    fun clearMessages() {
        _state.update { it.copy(error = null, successMessage = null) }
    }
}
